### ISSUE TITLE
ssrp运行时候出现因无相应的文件或目录导致无法读取！

### ISSUE THREAD

**Issue by zxlhhyccc** [fw876/helloworld#1120]
`````
Wed Feb 22 22:36:23 2023 daemon.crit dnsmasq[1]: cannot read /tmp/dnsmasq.d/dnsmasq-ssrplus.d/gfw_list.confNGFODn: No such file or directory
Wed Feb 22 22:36:23 2023 daemon.crit dnsmasq[1]: FAILED to start up
Wed Feb 22 22:36:28 2023 daemon.crit dnsmasq[1]: cannot read /tmp/dnsmasq.d/dnsmasq-ssrplus.d/gfw_list.confakIapJ: No such file or directory
Wed Feb 22 22:36:28 2023 daemon.crit dnsmasq[1]: FAILED to start up
Wed Feb 22 22:36:34 2023 daemon.crit dnsmasq[1]: cannot read /tmp/dnsmasq.d/dnsmasq-ssrplus.d/gfw_list.confcAHGdb: No such file or directory
Wed Feb 22 22:36:34 2023 daemon.crit dnsmasq[1]: FAILED to start up
`````

**Comment by jwkinko** [comment]
解决了吗？

**Comment by nebulite** [comment]
遇到了一样的问题，Lean的源，编译顺利，没有遇到问题，启动后系统日志里有一下error：
Sat Jun 15 17:12:25 2024 daemon.crit dnsmasq[1]: cannot read /tmp/dnsmasq.d/dnsmasq-ssrplus.d/gfw_list.confOAkHCe: No such file or directory
Sat Jun 15 17:12:25 2024 daemon.crit dnsmasq[1]: FAILED to start up
Sat Jun 15 17:12:29 2024 daemon.crit dnsmasq[1]: UBus error: Invalid argument
Sat Jun 15 17:12:29 2024 daemon.crit dnsmasq[1]: FAILED to start up
Sat Jun 15 17:12:34 2024 daemon.crit dnsmasq[1]: UBus error: Invalid argument
Sat Jun 15 17:12:34 2024 daemon.crit dnsmasq[1]: FAILED to start up
Sat Jun 15 17:12:39 2024 daemon.crit dnsmasq[1]: cannot read /tmp/dnsmasq.d/dnsmasq-ssrplus.d/gfw_list.confabdpbh: No such file or directory
Sat Jun 15 17:12:39 2024 daemon.crit dnsmasq[1]: FAILED to start up
Sat Jun 15 17:12:43 2024 daemon.crit dnsmasq[1]: UBus error: Invalid argument
Sat Jun 15 17:12:43 2024 daemon.crit dnsmasq[1]: FAILED to start up
Sat Jun 15 17:12:48 2024 daemon.crit dnsmasq[1]: UBus error: Invalid argument
Sat Jun 15 17:12:48 2024 daemon.crit dnsmasq[1]: FAILED to start up
Sat Jun 15 17:12:53 2024 daemon.crit dnsmasq[1]: UBus error: Invalid argument
Sat Jun 15 17:12:53 2024 daemon.crit dnsmasq[1]: FAILED to start up
Sat Jun 15 17:12:58 2024 daemon.crit dnsmasq[1]: UBus error: Invalid argument
Sat Jun 15 17:12:58 2024 daemon.crit dnsmasq[1]: FAILED to start up
Sat Jun 15 17:13:03 2024 daemon.crit dnsmasq[1]: UBus error: Invalid argument
Sat Jun 15 17:13:03 2024 daemon.crit dnsmasq[1]: FAILED to start up
Sat Jun 15 17:13:08 2024 daemon.crit dnsmasq[1]: UBus error: Invalid argument
Sat Jun 15 17:13:08 2024 daemon.crit dnsmasq[1]: FAILED to start up
Sat Jun 15 17:13:08 2024 daemon.info procd: Instance dnsmasq::cfg01411c s in a crash loop 6 crashes, 0 seconds since last crash
