### ISSUE TITLE
shadowsocks-rust编译失败

### ISSUE THREAD

**Issue by qwerttvv** [fw876/helloworld#1396]
两个机器，两个repo不同版本，都编译失败了

错误log在这里
https://github.com/qwerttvv/Router/actions/runs/7760138492/job/21165695572#step:12:1279
https://github.com/qwerttvv/Router/actions/runs/7757582252/job/21157375899#step:12:2318

希望可以revert这一个commit，改回以前的方式，当然，passwall那边也一样，都失败了
https://github.com/fw876/helloworld/commit/21b670bce7aeeb4c959e87171dfbf5ac7ef86866

另外生成固件，没有cache情况下这次时间翻倍了，而且还没编译成功，半路翻车了，不知道和这个commit有没有关系……

@Beginner-Go 
@coolsnowwolf

**Comment by AmberisMyShiba** [comment]
@qwerttvv 天灵update了shadowsocks-rust的Makefile，把直接下载预编译二进改为了从源码编译。但是在当前的制编译环境没有lang/rust支持。所以你可以等一等，或者用上一个commit。

**Comment by AmberisMyShiba** [comment]
> > @qwerttvv 天灵update了shadowsocks-rust的Makefile，把直接下载预编译二进改为了从源码编译。但是在当前的制编译环境没有lang/rust支持。所以你可以等一等，或者用上一个commit。
> 
> 看看上游最终啥方案吧，能回退到以前直接用bin最好

我看了以下你的云编译的log.似乎是你的rust版本过低引起的。编译shadowsocks-rust需要1.170.0以上的编译器，而当前的rustc版本是1.67.1

> [2303](https://github.com/qwerttvv/Router/actions/runs/7757582252/job/21157375899#step:12:2304)
error: package `clap_builder v4.4.18` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.67.1
[2304](https://github.com/qwerttvv/Router/actions/runs/7757582252/job/21157375899#step:12:2305)
Either upgrade to rustc 1.70.0 or newer, or use
[2305](https://github.com/qwerttvv/Router/actions/runs/7757582252/job/21157375899#step:12:2306)
cargo update clap_builder@4.4.18 --precise ver
