### ISSUE TITLE
forwarding settings feature

### ISSUE THREAD

**Issue by predators46** [fw876/helloworld#701]
Hy @coolsnowwolf 

can you add the forwarding settings feature
![Screenshot_2021-10-27_071813](https://user-images.githubusercontent.com/31931530/138974793-621033c0-2f07-4b50-9d1a-0271d00d8a06.jpg)

**Comment by 1715173329** [comment]
![image](https://user-images.githubusercontent.com/22235437/139531861-dacecc08-2bf2-480a-8a0d-9d4201545d72.png)

I think it's good enough for common usage.
Hacking it by yourself if in need.

**Comment by KevinMX** [comment]
Although we can do some small changes to /etc/init.d/shadowsocksr to change proxied ports:

https://github.com/fw876/helloworld/blob/9ed9a8ea96f77499977b1f3c5380e582a0424354/luci-app-ssr-plus/root/etc/init.d/shadowsocksr#L780

It's still not convenient enough.

You can't simply change it in WebUI and you have to change it via SSH.

This commit by me https://github.com/fw876/helloworld/commit/0efed3746dbba659757211b4bcd0cf3a37b4f995 (or PR https://github.com/fw876/helloworld/pull/305) is actually the issue I ran into when I tried to compile openwrt and when I was syncing the source code, some of them were using port 9148/git and not proxied by SSRP+/helloworld. And I get this problem again few days ago when trying to connect a minecraft server which need to be proxied, but I do not want to proxy all ports since I have BT/PT tasks running in the background and I don't want to get into trouble about DMCA $h*t.

So personally I would be happy to see if there's an easy option in LuCI WebUI for users to change the proxied ports. This is much more on a feature request side rather than an issue, and it's up to you guys to decide to add it, or not.

**Comment by predators46** [comment]
> ![image](https://user-images.githubusercontent.com/22235437/139531861-dacecc08-2bf2-480a-8a0d-9d4201545d72.png)
> 
> I think it's good enough for common usage. Hacking it by yourself if in need.

can you share like in the photo. i don't really understand making it exist in luci-app-shadowsocksr

**Comment by predators46** [comment]
> Although we can do some small changes to /etc/init.d/shadowsocksr to change proxied ports:
> 
> https://github.com/fw876/helloworld/blob/9ed9a8ea96f77499977b1f3c5380e582a0424354/luci-app-ssr-plus/root/etc/init.d/shadowsocksr#L780
> 
> It's still not convenient enough.
> 
> You can't simply change it in WebUI and you have to change it via SSH.
> 
> This commit by me [0efed37](https://github.com/fw876/helloworld/commit/0efed3746dbba659757211b4bcd0cf3a37b4f995) (or PR #305) is actually the issue I ran into when I tried to compile openwrt and when I was syncing the source code, some of them were using port 9148/git and not proxied by SSRP+/helloworld. And I get this problem again few days ago when trying to connect a minecraft server which need to be proxied, but I do not want to proxy all ports since I have BT/PT tasks running in the background and I don't want to get into trouble about DMCA $h*t.
> 
> So personally I would be happy to see if there's an easy option in LuCI WebUI for users to change the proxied ports. This is much more on a feature request side rather than an issue, and it's up to you guys to decide to add it, or not.

I wish this was on shadowsocksr plus. I'm currently using a passwall

**Comment by KevinMX** [comment]
> I wish this was on shadowsocksr plus. I'm currently using a passwall
I got some stability issues with passwall, sometimes it just crash my DNS resolution, although it's really flexible... I'm sticking with SSRP+ right now.
